import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Blessed Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.variable} antialiased`}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
